ALTER TABLE "LiveCamera" ADD COLUMN "alertEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "LiveCamera" ADD COLUMN "alertFrom" TEXT NOT NULL DEFAULT '20:00';
ALTER TABLE "LiveCamera" ADD COLUMN "alertTo" TEXT NOT NULL DEFAULT '06:00';
ALTER TABLE "LiveCamera" ADD COLUMN "alertRaisedOn" TEXT;
